### ISSUE TITLE
wrong balance ?

### ISSUE THREAD

**Issue by salanfe** [zeppelinos/labs#104]
hi,

https://github.com/zeppelinos/labs/blob/a8c00cf6ff9ac8fb9fef87f68da4c2d1891941a5/upgradeability_using_inherited_storage/test/Upgradeable.js#L32

shouldn't the balance be 190 ?

1) mint 100 to sender
2) mint 100 to sender
3) transfer 10 from sender to receiver

=> balance should be 190 ?! (100 + 100 -10 = 190)

thx for those great proxy patterns

**Comment by facuspagnuolo** [comment]
No, please note that we are minting 1000 tokens in during the [initialization process ](https://github.com/zeppelinos/labs/blob/a8c00cf6ff9ac8fb9fef87f68da4c2d1891941a5/upgradeability_using_inherited_storage/contracts/test/Token.sol#L12)
