### ISSUE TITLE
Review and polish inline documentation for main projects

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/labs#114]
- [ ] zos-cli
- [ ] zos-lib

**Comment by fiiiu** [comment]
Removed kernel.

**Comment by fiiiu** [comment]
Be sure to add `@dev` in multiline `@param` comments:
https://github.com/zeppelinos/zos-lib/pull/95#discussion_r187666467

**Comment by elopio** [comment]
Docstrings to smart contracts reviewed in https://github.com/zeppelinos/zos-lib/pull/143

**Comment by fiiiu** [comment]
Closed in favor of https://github.com/zeppelinos/zos-cli/issues/219 and https://github.com/zeppelinos/zos-lib/issues/145.
