### ISSUE TITLE
Gas used for delegatecall

### ISSUE THREAD

**Issue by yondonfu** [zeppelinos/labs#2]
On L21 in `Proxy`, the fallback function executes this inline assembly delegatecall:

`let result := delegatecall(sub(gas, 10000), _impl, add(data, 0x20), mload(data), 0, 0)`

Does gas need to be subtracted from the currently available gas - couldn't all the gas be sent after EIP150 (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md)? My understanding is that before EIP150 you had to subtract enough gas for the opcode (i.e. DELEGATECALL), but after EIP150, 1/64 of the available gas is automatically reserved for the opcode and 63/64 of the available gas is used in the actual call.

**Comment by androolloyd** [comment]
Perhaps its pre EIP-150, I would like to know the answer to this as well.

**Comment by facuspagnuolo** [comment]
@yondonfu good catch and sorry for the delay!
We've been looking into the EIP-150 details and testing to see how the available gas works on delegatecalls. You are definitely right, 1/64 parts of the available gas is automatically reserved on a delegate call. 

Thanks for your collaboration and bringing it up!

**Comment by facuspagnuolo** [comment]
Fixed in [bdb558d](https://github.com/zeppelinos/labs/commit/bdb558d881328396d2105f2e24af02806b076524)
