### ISSUE TITLE
Tooling for managing upgrades

### ISSUE THREAD

**Issue by albpal** [zeppelinos/labs#3]
Hi amigos!

I'm reviewing your awesome ZeppelinOS and I'm not sure if you will provide tools for managing upgrades on first instance with kernel + contract framework or it will be develop later on Platform & SDK tools. I'm thinking to contribute on some way on this but I'd like to know it to align roadmaps.

As far I have understood you will first provide smart contracts that are upgradables and later tooling to manage these contract and perform migrations/upgrades if needed. Is it correct?

**Comment by facuspagnuolo** [comment]
Hi @albpal! Thanks for asking!

As you mentioned, we will start building the kernel, an on-chain set of libraries with built-in upgradeability, and contract development tools. This does include tools for managing the opt-in upgrades of the upgradeable contracts included in the kernel. Then, we will start with the platform and SDK which will continue improving the upgradeability mechanisms and tooling, among other things.

You can take a look at [this post](https://blog.zeppelinos.org/zeppelin_os-development-roadmap-part-two/) that describes further details of our roadmap for this year.

**Comment by albpal** [comment]
Thanks @facuspagnuolo! Your work is awesome.
