### ISSUE TITLE
Finalize ZEP token contract 

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/labs#33]
Consider adding the following functionality:
- [x] `BurnableToken`
- [x] `MintableToken` (needed?)
- [x] `PausableToken`
- [x] `UpgradeableToken`

**Comment by spalladino** [comment]
We have a ZepToken in the [kernel-registry](https://github.com/zeppelinos/kernel-registry/blob/master/contracts/ZepToken.sol) repo, as well as another in a [standalone repo](https://github.com/zeppelinos/zep-token). 

I'd suggest deleting the standalone repo, using the one from the kernel registry, and closing this issue. @maraoz WDYT?

**Comment by maraoz** [comment]
zeppelinos/zep-token repo removed, but I'm keeping the issue open because the current version in https://github.com/zeppelinos/kernel/blob/84c499327aef60a06924d418a744c61d5e3f00d3/contracts/ZepToken.sol is not upgradeable.
