### ISSUE TITLE
Analyze alternative to use fixed assembly storage for proxy metadata

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/labs#52]
See if we can manage to have some fixed storage for proxy metadata (owner, implementation, etc) using assembly code, as an alternative to share contract storage structures.

**Comment by spalladino** [comment]
The idea is to store those specific variables at a hardcoded address in the contract's storage, such as `sha256("zeppelinos.proxy.owner")`. Ensure there is no Solidity construct that could allow this value to be overridden.
