### ISSUE TITLE
Migrate kernel folder to separate registry repository

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#57]
The Kernel registry and management is mature enough to be moved to its own repo at https://github.com/zeppelinos/registry. Move it there, delete the existing `kernel` folder, and close issues #42, #37, #38. #35.

**Comment by facuspagnuolo** [comment]
Cool! Two minor things:
- What do you think about renaming the repo to `kernel`? 
- I would leave the lab repo as it is to show how we've been developing and spiking different ideas, thoughts? (e.g. we didn't remove upgradeability stuff)

**Comment by spalladino** [comment]
Not sure if I like `Kernel`, it may get confused with a particular kernel instance. Shall we compromise at `kernel-registry`?

**Comment by spalladino** [comment]
Consider [keeping development history](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) of the Kernel folder

**Comment by facuspagnuolo** [comment]
Closing in favor of https://github.com/zeppelinos/kernel-registry
