### ISSUE TITLE
Review naming for Kernel and Core

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#68]
The name Kernel may be confusing, as it evokes what manages the rules of the system (currently named ZepCore), instead of a set of shared libraries. Consider using _Standard Library_  as it may be more accurate, and it is also used in the whitepaper.

Should Kernel be renamed, also review the naming of ZepCore and other `kernel-registry` contracts.

**Comment by maraoz** [comment]
Naming reviewed offline, being worked on https://github.com/zeppelinos/upgradeability-lib/pull/44 and https://github.com/zeppelinos/kernel/pull/22
