### ISSUE TITLE
Preprocessor for adapting contracts to be valid backing implementations for proxies

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#71]
With the [fixed proxy model](https://github.com/zeppelinos/labs/tree/master/upgradeability_using_fixed_storage), any Solidity contract can be a backing implementation for a proxy as long as it does not rely on any constructor logic. Such logic needs to be moved to an `initialize` method, to be called only once.

Research building a preprocessing step for automating this procedure with existing contracts.

**Comment by frangio** [comment]
I don't think codemod is the right concept here because it is apparently a tool used for refactors.

When I proposed this idea I was talking about a preprocessing step to be always run before deploying a new version of a contract.

**Comment by frangio** [comment]
Alternatively a linter to validate, instead of a preprocessor.

**Comment by facuspagnuolo** [comment]
@spalladino can I close this one since https://github.com/zeppelinos/labs/pull/127 was already merged?
