### ISSUE TITLE
Register zos-core ProxyController as a kernel instance

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#76]
In order to bootstrap a new project with zOS, a user needs to deploy a new ProjectController, which includes a registry (and maybe a factory). This requires a full deploy, and is not upgradeable; it'd be better to allow the user to request a proxy of a ProxyController for their own projects.

This can be done by registering a ProxyController as a zOS kernel instance, so a dev can manually (or assisted by a CLI) request a new proxy for it, and use it in their project.

**Comment by facuspagnuolo** [comment]
It's amazing that most of these terms don't exist anymore. We are already working with on-chain factories to deal with proxies creation. Closing this issue
