### ISSUE TITLE
Development and operation CLI tool

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#87]
Tool to develop and operate userland apps
includes #72

**Comment by ajsantander** [comment]
I've been working on a demo app that uses much of the deploy utilities currently in the kernel-registry repo, but adds a layer of utilities. Most importantly, it keeps track of deployment json files, one for each network:
"deploy_data.development.json" <- this one is usually git ignored
"deploy_data.ropsten.json"
"deploy_data.mainnnet.json"

The structure of one of these files looks something like this:
```
{
  "controllerAddress": "0x3fc678ce3f5b777f5556b990cfe341d54c6c1c1e",
  "contracts": {
    "Crowdsale": {
      "proxyAddress": "0x6144c2a9876d74e990d042bb11a0b1b2d2e5a5ae",
      "versions": {
        "0": "0xe4dc4e740016b7df5e313e6e12b84d3012fb9c21",
        "1": "0x70a2dcf0571444fb102aeed792a9d8996a3676a7"
      },
     "Wallet": {
      "proxyAddress": "...",
      "versions": {
        "0": "...",
      }
    }
  }
}
```
The deploy script traverses this file understanding what needs to be done and prompting the user for confirmation. For example, if it does not find a `controllerAddress`, it can create and deploy a new ProjectController. Or, if it finds an invalid address in one of the vesions of a contract, it can imply the intention of the user to deploy a new version and automatically takes the user through the process of deploying a new version.

**Comment by spalladino** [comment]
Discussion with @ajsantander on the **operation** part of the CLI.

Keep a single file that describes the application `Package`, plus one file per-network that describes its deployment status, and keeps track of proxies created. 

Example of general package description:

```json
{
  "package": {
    "versions": {
      "1.0": {
        "contracts": {
          "Basil": "Basil_v0"
        },
        "stdlib": {
          "name": "OpenZeppelin",
          "version": "1.7.0"
        }
      },
      "1.1": {
        "contracts": {
          "Basil": "Basil_v1",
          "Rosemary": "Rosemary_v1"
        },
        "stdlib": {
          "name": "OpenZeppelin",
          "version": "1.8.0"
        }
      }
    }
  }
}
```

Example of the per-network file:
```json
{
  "proxies": {
    "Basil": [
      {
        "proxy": "0x010",
        "version": "1.0",
      },
      {
        "proxy": "0x011",
        "version": "1.1"
      }
    ],
    "ERC721Token": [
      {
        "proxy": "0x210",
        "version": "1.1"
      }
    ]
  },
  "package": {
    "versions": {
      "1.0": {
        "contracts": {
          "Basil": "0x123"
        },
        "stdlib": {
          "address": "0x456"
        }
      },
      "1.1": {
        "contracts": {
          "Basil": "0x123",
          "Rosemary": "0x124"
        },
        "stdlib": {
          "address": "0x457"
        }
      }
    }
  }
}
```

**Comment by spalladino** [comment]
This file would be managed by a CLI tool, similar to npm, with the following commands:

### init: versionName, stdlib?, network?

Initializes a new json file, starting with the specified versionName and stdlib (if set). Optionally, it also deploys a to the network new `PackagedAppManager` with its `Package` and an `AppDirectory` for the initial version. When deploying, it also updates the per-network json file.

### addImplementation: contractName, contractName:contractAlias, ..., network?

Registers the contract names in the current version, storing them in the general json file. Optionally, it also deploys the contracts and adds them to the AppProvider for the current version (updating the per-network json file).

NTH: throw a warning if the contract does not comply with the zOS checklist (such as having a constructor)

### createProxy: contractName, args?, network

Creates a new proxy in the specified network, updating the per-network proxy, for the current version. Optionally calls an initialize method with the supplied args (argTypes can be extracted from the contract implementation, they don't need to be specified).

Before running, should check that the Package is up-to-date in the network.

### upgradeProxy: proxyAddress, network

Upgrades a proxy to the current app version in the specified network.

NTH: support upgradeToAndCall to run migrations.

NTH: support upgrading all proxies with a single command.

### newVersion: versionName, stdlib?, network?

Creates new version in the general json file. Optionally creates the corresponding contracts in the network (AppDirectory in the Package), and moves the AppManager of that network to that version.

### freezeVersion: versionName, network?

Freezes a version. Flags it as frozen in the general json file, and optionally freezes it in a network (after checking that it is up-to-date).

### install: network

Runs all newVersion and addImplementation operations needed to get the AppManager in the target network in-sync with the global package file. Name of this command is pending review.

**Comment by martriay** [comment]
Based on offline discussions, we have ended up with this file structures:

#### Package file (`package.zos.json`)
```
{
  "name": "Herbs",
  "version": "1.1.0",
  "contracts": {
    "Basil": "Basil_v1.sol",
    "Rosemary": "Rosemary_v1.sol"
  },
  "stdlib": {
    "name": "OpenZeppelin",
    "version": "1.8.0"
  }
}
```

#### Network file (`package.zos.ropsten.json`)
```
{
  "app": {
    "address": "0x30",
    "version": "1.1"
  },
  "proxies": {
    "Basil": [
      {
        "address": "0x010",
        "version": "1.0",
      },
      {
        "address": "0x011",
        "version": "1.1"
      }
    ],
    "ERC721Token": [
      {
        "address": "0x210",
        "version": "1.1"
      }
    ]
  },
  "package": {
    "contracts": {
      "Basil": "0x123",
      "Rosemary": "0x456"
    },
    "stdlib": {
      "address": "0x456"
    }
  }
}
```

**Comment by maraoz** [comment]
Already implemented in https://github.com/zeppelinos/zos-cli
